### PR TITLE
Add spacecraft benchmark

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by lbenet** [comment]
Seems that some dependency might be needed for tests to pass; see travis output [here](https://travis-ci.com/github/JuliaReach/ARCH2020_NLN_RE/builds/172708466#L2219).

**Comment by mforets** [comment]
I've pushed an update which passes in the latest release of ReachabilityAnalysis (v0.7.2) -- that's [this notebook](https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/2020/Week26/Spacecraft_NLN_RAv0.7.2.ipynb).

But that means that we have to update the Manaifest.toml file in this repo, to use the latest release of RA (https://github.com/JuliaRegistries/General/pull/16879). Should we do that update this PR or in a separate one?

**Comment by lbenet** [comment]
> Should we do that update this PR or in a separate one?

As you prefer; this PR is fine for me.

**Comment by mforets** [comment]
The last commit updates the project files to use ReachabilityAnalysis#v0.7.2. For future reference, i've written the instructions on https://github.com/JuliaReach/ARCH2020_NLN_RE/wiki/Instructions-for-creating-this-RE

In my machine running this RE gives

```julia
JuliaReach, PRDE20, I, 1, 1.167377173, 3.3e-20
JuliaReach, PRDE20, P, 1, 3.122000943, 6.5e-21
JuliaReach, PRDE20, IP, 1, 2.335315413, 1.0e-20
JuliaReach, CVDP20, μ=1.0, 1, 0.314111107
JuliaReach, CVDP20, μ=2.0, 1, 28.101097421000002
JuliaReach, LALO20, W=0.01, 1, 0.8215832540000001, 0.0042
JuliaReach, LALO20, W=0.05, 1, 1.41548797, 0.017
JuliaReach, LALO20, W=0.1, 1, 1.199894708, 0.033
JuliaReach, LOVO20, , 1, 6.309518315, 0.0022, 0.182
JuliaReach, SPRE20, , 1, 16.923278619
```

**Comment by mforets** [comment]
The build failed because i had forgotten to add the plots packages to the environment. This is a case where, as we saw with  @dpsanders,  `using foo` doesn't fail even if `foo` was not explicitly added to the environment.

**Review by lbenet — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by lbenet** [comment]
Please, go ahead and merge this!

**Pull request merged**
