### PR TITLE
Let travis check the docker container

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by mforets** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

Seems like the job hits maximum time limit. Perhaps there are ways to extend such limit? (for free)

**Comment by mforets** [comment]
.. there's also Docker container github actions: https://help.github.com/en/actions/creating-actions/creating-a-docker-container-action

**Comment by mforets** [comment]
> Seems like the job hits maximum time limit. Perhaps there are ways to extend such limit? (for free)

commit f73458d tries with the `travis_wait` option (docs [here](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received))

**Comment by lbenet** [comment]
I think the container part runs fine; running out of time might be related to the `script` part.

**Comment by mforets** [comment]
the "travis CI - branch" passed. maybe the travis CI "PR" failed because there is no travis script in master.. ? i suggest to merge this one and try running travis in  `master` again afterwards.

**Comment by lbenet** [comment]
Ok. Merging

**Pull request merged**
